input {
  tcp {
    port => 5000
    # codec => multiline {
    #   #type => "all" # no type means for all inputs
    #   pattern => "(^.+Exception: .+)|(^\s+at .+)|(^\s+... \d+ more)|(^\s*Caused by:.+)"
    #   what => "previous"
    # }
  }
  gelf {
    port => 12201
    # codec => multiline {
    #   #type => "all" # no type means for all inputs
    #   pattern => "(^.+Exception: .+)|(^\s+at .+)|(^\s+... \d+ more)|(^\s*Caused by:.+)"
    #   what => "previous"
    # }
  }
  syslog {
    port => 25826
    port => 51000
    port => 52000
    # codec => multiline {
    #   #type => "all" # no type means for all inputs
    #   pattern => "(^.+Exception: .+)|(^\s+at .+)|(^\s+... \d+ more)|(^\s*Caused by:.+)"
    #   what => "previous"
    # }
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_rogram}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"
      }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    syslog_pri { }
    date {
      match => [ "timestamp", "ISO8601" ]
      }
    }
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
    index => "calahan_index"
  } 
}

filter {
  if "docker/" in [program] {
    mutate {
      add_field => {
        "container_id" => "%{program}"
      }
    }
    mutate {
      gsub => [
        "container_id", "docker/", ""
      ]
    }
    mutate {
      update => [
        "program", "docker"
      ]
    }
  }
  multiline {
    #type => "all" # no type means for all inputs
    pattern => "(^.+Exception: .+)|(^\s+at .+)|(^\s+... \d+ more)|(^\s*Caused by:.+)"
    what => "previous"
  }
  # Remove all new lines from message
  # mutate {
  #   gsub => [ "message", "\r", "" ]
  # }
  # grok {
  #   match => [ "message", "(?m)%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:severity} %{GREEDYDATA:message}" ]
  #   overwrite => [ "message" ]
  # }
  # date {
  #     match => [ "timestamp" , "yyyy-MM-dd HH:mm:ss,SSS" ]
  # }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}